export const sportPositions = {
  football: [
    'PRODUCER',
    'ASST PROD',
    'DIRECTOR',
    'ASST DIRECTOR',
    'TECHNICAL DIR',
    'GRAPHICS',
    'BUG OP',
    'REPLAY EVS 1',
    'REPLAY EVS 2',
    'VIDEO',
    'EIC',
    '2ND ENG',
    'AUDIO 1',
    'AUDIO 2',
    'CAMERA 1',
    'CAMERA 2 HIGH EZ',
    'CAMERA 3 LOW EZ',
    'CAMERA 4 N HH',
    'CAMERA 5 S HH',
    'CAMERA 6',
    'UTILITY',
    'UTILITY',
    'UTILITY',
    'INTERN',
    'OBSERVER',
    'OBSERVER'
  ],
  baseball: [
    'PRODUCER',
    'ASST PROD',
    'DIRECTOR',
    'ASST DIRECTOR',
    'TECHNICAL DIR',
    'GRAPHICS',
    'BUG OP',
    'REPLAY EVS 1',
    'REPLAY EVS 2',
    'REPLAY EVS 3',
    'VIDEO',
    'EIC',
    '2ND ENG',
    'AUDIO 1',
    'AUDIO 2',
    'CAMERA 1',
    'CAMERA 2',
    'CAMERA 3',
    'CAMERA 4',
    'CAMERA 5',
    'CAMERA 6',
    'UTILITY',
    'UTILITY',
    'TECH MANAGER',
    'TOC',
    'OBSERVER',
    'OBSERVER'
  ],
  mensBasketball: [
    'PRODUCER',
    'ASST PROD',
    'DIRECTOR',
    'ASST DIRECTOR',
    'TECHNICAL DIR',
    'GRAPHICS',
    'BUG OP',
    'REPLAY EVS 1',
    'REPLAY EVS 2',
    'REPLAY EVS 3',
    'EIC',
    'VIDEO',
    '2ND ENG',
    'AUDIO 1',
    'AUDIO 2',
    'CAMERA 1',
    'CAMERA 2',
    'CAMERA 3',
    'CAMERA 4',
    'CAMERA 5',
    'CAMERA 6',
    'UTILITY',
    'UTILITY',
    'TECH MANAGER',
    'TOC',
    'OBSERVER',
    'OBSERVER'
  ],
  womensBasketball: [
    'PRODUCER',
    'ASST PROD',
    'DIRECTOR',
    'ASST DIRECTOR',
    'TECHNICAL DIR',
    'GRAPHICS',
    'BUG OP',
    'REPLAY EVS 1',
    'REPLAY EVS 2',
    'REPLAY EVS 3',
    'VIDEO',
    'EIC',
    '2ND ENG',
    'AUDIO 1',
    'AUDIO 2',
    'CAMERA 1',
    'CAMERA 2',
    'CAMERA 3',
    'CAMERA 4',
    'CAMERA 5',
    'CAMERA 6',
    'UTILITY',
    'UTILITY',
    'TECH MANAGER',
    'TOC',
    'OBSERVER',
    'OBSERVER'
  ],
  volleyball: [
    'PRODUCER',
    'ASST PROD',
    'DIRECTOR',
    'ASST DIRECTOR',
    'TECHNICAL DIR',
    'GRAPHICS',
    'BUG OP',
    'REPLAY EVS 1',
    'REPLAY EVS 2',
    'REPLAY EVS 3',
    'VIDEO',
    'EIC',
    '2ND ENG',
    'AUDIO 1',
    'AUDIO 2',
    'CAMERA 1',
    'CAMERA 2',
    'CAMERA 3',
    'CAMERA 4',
    'CAMERA 5',
    'CAMERA 6',
    'UTILITY',
    'UTILITY',
    'TECH MANAGER',
    'TOC',
    'OBSERVER',
    'OBSERVER'
  ],
  soccer: [
    'PRODUCER',
    'ASST PROD',
    'DIRECTOR',
    'ASST DIRECTOR',
    'TECHNICAL DIR',
    'GRAPHICS',
    'BUG OP',
    'REPLAY EVS 1',
    'REPLAY EVS 2',
    'REPLAY EVS 3',
    'VIDEO',
    'EIC',
    '2ND ENG',
    'AUDIO 1',
    'AUDIO 2',
    'CAMERA 1',
    'CAMERA 2',
    'CAMERA 3',
    'CAMERA 4',
    'CAMERA 5',
    'CAMERA 6',
    'UTILITY',
    'UTILITY',
    'TECH MANAGER',
    'TOC',
    'OBSERVER',
    'OBSERVER'
  ]
}; 